### ISSUE TITLE
Data base implementation

### ISSUE THREAD

**Issue by FScociety** [FScociety/jetpack-thingy#15]
- [x] setup DataBase server
- [x] Implementation of DataBase into Java
- [x] Saving and Loading API for the game
- [x] Password Encryption

**Comment by pauldunz** [comment]
Already working functions: 
- [x] create_acc()
- [x] login()
- [x] get_user()


To do functions:
- [x] Save new Highscore
- [x] Save current amount of coins

**Comment by FScociety** [comment]
Erotika
